# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)

    - task: DockerInstaller@0
      displayName: "Instalar Docker"

    - script: |
        az acr login --name containerregistryricardosilverio
        docker build -t containerregistryricardosilverio.azurecr.io/unyleya_ricardosilverio:$(tag) -f /var/lib/jenkins/myagent/_work/1/s/azure-vote/Dockerfile .
      displayName: "Build da imagem Docker"

    - script: |
        docker push containerregistryricardosilverio.azurecr.io/unyleya_ricardosilverio:$(tag)
      displayName: "Enviar imagem para ACR"

# Adicionando estágio de Deploy via Helm
- stage: DeployHelm
  displayName: Deploy via Helm
  jobs:
  - job: DeployToKubernetes
    displayName: "Implantação no Kubernetes"
    pool:
      vmImage: ubuntu-latest
      name: 'Default'
      environment: ricardosilveriokubernets
    
    steps:
    - task: HelmInstaller@0
      inputs:
        helmVersion: 'latest'

    - script: |
        helm version
        helm list --all
        helm repo list
        kubectl get nodes
      displayName: "Verificar Helm e Releases"

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'AKSClusterRicardoSilverio-default'
        namespace: 'kube-system'
        command: 'upgrade'
        chartName: 'aks-managed-overlay-upgrade-data'
        releaseName: 'overlay-upgrade-data-addon-0.1.0-3306ac2d69cd70a5d127324597f7996aab68115b'
        arguments: '--set image.repository=containerregistryricardosilverio.azurecr.io/unyleya_ricardosilverio,image.tag=$(tag)'